import React from 'react'
import LoadingState from '../../components/ui/LoadingState.jsx'
import ErrorState from '../../components/ui/ErrorState.jsx'
import { getHazards, getDraftWarning } from '../../data/mock/authorityData.js'
import { useTranslation } from '../../i18n/translations.js'

export default function AuthorityAlerts({ data, loading, error, onRetry }) {
  const { t } = useTranslation()

  if (loading) return <LoadingState />
  if (error) return <ErrorState message={error} onRetry={onRetry} />

  const hazards = getHazards(data)
  const draftWarning = getDraftWarning(data) || {
    id: 'warning-ernakulam-001',
    targetAudience: ['small_fishing_vessels', 'coastal_fishing_communities'],
    title: 'Marine conditions caution for small vessels — Kochi, Kerala coast',
    message:
      'Location is inside Demo Marine Protected Area; commercial fishing is prohibited inside the boundary. All marine parameters (wave 0.98m, wind 14.7 km/h) are within favourable operating limits for small fishing boat. Small fishing vessels are advised to review the latest official marine advisories before departure.',
    validFrom: '2026-09-07T15:54:00+05:30',
    validUntil: '2026-09-08T15:54:00+05:30',
    targetAreas: ['Kochi, Kerala coast'],
    disclaimer:
      'Draft generated by ORCA for authority review. It is not an official warning until approved and sent through authorised channels.',
  }

  return (
    <div className="space-y-6 pb-12 animate-fade-in">
      {/* Section Header matching code.html */}
      <div className="space-y-1 pb-2 border-b border-slate-200/60">
        <h1 className="text-2xl font-bold text-slate-900 tracking-tight">
          {t('Maritime Warning & Response')}
        </h1>
        <p className="text-sm font-medium text-slate-500">
          {t('Review generated advisories and active hazards')}
        </p>
      </div>

      {/* Split Layout: Workflow Card & Active Hazards matching code.html */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left: Draft Warning Workflow (8 cols) */}
        <div className="lg:col-span-8 space-y-4">
          <h2 className="text-base font-bold text-slate-900">{t('Draft Warning Workflow')}</h2>

          <div className="bg-white border border-slate-200 rounded-2xl p-6 sm:p-8 shadow-sm space-y-6 border-l-4 border-l-amber-500">
            {/* Draft Header Metadata */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2">
              <div className="flex items-center gap-3">
                <span className="text-xs font-bold px-2.5 py-0.5 rounded bg-amber-100 text-amber-800 uppercase tracking-wider">
                  {t('Draft')}
                </span>
                <span className="text-xs font-mono text-slate-500">
                  ID: {draftWarning.id || 'warning-ernakulam-001'}
                </span>
              </div>
              <div className="text-xs text-slate-500">
                <span className="font-medium text-slate-400">{t('Target:')}</span>{' '}
                {draftWarning.targetAudience?.map((aud) => t(aud)).join(', ') || 'small_fishing_vessels, coastal_fishing_communities'}
              </div>
            </div>

            {/* Warning Title & Narrative */}
            <div className="space-y-3">
              <h3 className="text-xl font-bold text-slate-900 leading-tight">
                {t(draftWarning.title)}
              </h3>
              <p className="text-sm text-slate-600 leading-relaxed">
                {t(draftWarning.message)}
              </p>
            </div>

            {/* Time Validity Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="bg-slate-50/70 border border-slate-200 rounded-xl p-3.5">
                <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{t('Valid From')}</p>
                <p className="text-sm font-semibold text-slate-800 mt-0.5">
                  {draftWarning.validFrom ? new Date(draftWarning.validFrom).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '7 Sep 2026 at 3:54 PM'}
                </p>
              </div>
              <div className="bg-slate-50/70 border border-slate-200 rounded-xl p-3.5">
                <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{t('Valid Until')}</p>
                <p className="text-sm font-semibold text-slate-800 mt-0.5">
                  {draftWarning.validUntil ? new Date(draftWarning.validUntil).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '8 Sep 2026 at 3:54 PM'}
                </p>
              </div>
            </div>

            {/* Target Areas Box */}
            <div className="bg-slate-50/70 border border-slate-200 rounded-xl p-3.5">
              <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2">{t('Target Areas')}</p>
              <div className="flex flex-wrap gap-2">
                {(draftWarning.targetAreas || ['Kochi, Kerala coast']).map((area, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-white text-slate-700 border border-slate-200 shadow-2xs"
                  >
                    {t(area)}
                  </span>
                ))}
              </div>
            </div>

            {/* Legal/Workflow Disclaimer */}
            <div className="flex items-start gap-3 p-4 bg-sky-50/60 border border-sky-100 rounded-xl text-xs text-sky-800">
              <svg className="w-4 h-4 text-sky-600 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" />
              </svg>
              <span>{t(draftWarning.disclaimer)}</span>
            </div>

            {/* Action Controls */}
            <div className="flex flex-col sm:flex-row sm:items-center gap-3 pt-2">
              <button
                className="inline-flex items-center justify-center px-5 py-2.5 rounded-xl bg-sky-600 text-white text-sm font-semibold hover:bg-sky-700 active:scale-95 transition shadow-sm opacity-90 cursor-not-allowed"
                type="button"
                disabled
              >
                {t('Review Draft')}
              </button>
              <span className="text-xs italic text-slate-400">
                {t('Workflow actions (Approve/Publish) are not implemented in MVP.')}
              </span>
            </div>
          </div>
        </div>

        {/* Right: Active Hazards Card (4 cols) */}
        <div className="lg:col-span-4 space-y-4">
          <h2 className="text-base font-bold text-slate-900">{t('Active Hazards')}</h2>

          <div className="space-y-4">
            {hazards.map((h) => (
              <div
                key={h.id}
                className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-3 border-l-4 border-l-sky-500"
              >
                <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-sky-700">
                  <svg className="w-4 h-4 text-sky-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" />
                  </svg>
                  {t(h.severity === 'watch' ? 'Watch' : 'Advisory')}
                </div>
                <h3 className="text-base font-bold text-slate-900">{t(h.title)}</h3>
                <p className="text-xs text-slate-600 leading-relaxed">{t(h.message)}</p>
                <p className="text-[11px] font-mono text-slate-400 pt-2 border-t border-slate-100">
                  {t('Source:')} {h.sourceRef || 'neer-geofence'}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
